apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loan-business
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/it-hieupq/loan-business-deployment.git
    targetRevision: HEAD
    path: .
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
